// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiErrorKind } from "./ApiErrorKind";

/**
 * A structured v2 API error. Serialized as `{ "kind", "message" }`.
 */
export type ApiError = { kind: ApiErrorKind, message: string, };
