// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable error kind for the v2 API. [`ApiErrorKind::ResyncRequired`]
 * signals that a consumer's event cursor has been evicted from the bridge ring
 * and it must refetch the snapshot and the current message page instead of
 * guessing the missing state.
 */
export type ApiErrorKind = "bad_request" | "not_found" | "unauthorized" | "conflict" | "internal" | "resync_required";
