// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDto } from "./ApprovalDto";
import type { ContextBudgetDto } from "./ContextBudgetDto";
import type { PartialDto } from "./PartialDto";
import type { SessionStateDto } from "./SessionStateDto";
import type { TodoDto } from "./TodoDto";

/**
 * Full application state snapshot returned by `GET /api/v2/state`.
 *
 * `event_cursor` is the current global bridge cursor; the client subscribes
 * from this position so no event is lost between the snapshot and the SSE
 * stream. `protocol_version` lets a frontend reject an incompatible server
 * instead of misreading state. New fields must be additive.
 */
export type AppSnapshotV2 = { protocol_version: number,
/**
 * Current process-global event cursor; subscribe from here.
 */
event_cursor: bigint, active_session: string | null, sessions: Array<SessionStateDto>, provider: string, model: string, mode: string,
/**
 * Serialized pending approval of the oldest waiting session, if any.
 */
approval: ApprovalDto | null, todos: Array<TodoDto>,
/**
 * Context capacity of the active session, computed by the core (the single
 * authority). `None` when no session is active.
 */
context: ContextBudgetDto | null,
/**
 * The active session's persisted incomplete assistant answer, if any
 * (survives a restart so an interrupted stream is still visible).
 */
assistant_partial: PartialDto | null, };
