// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-session context capacity, computed by the core.
 *
 * The core is the single authority for context capacity; the TUI must not
 * infer capacity from local character counts. `safe_input_tokens` is the
 * window minus the output reservation minus current usage — the budget a new
 * user message must fit into.
 */
export type ContextBudgetDto = {
/**
 * The model's context window in tokens. `None` when the model is unknown
 * and no explicit `context_window_tokens` is configured.
 */
context_window_tokens: bigint | null,
/**
 * Current estimated used tokens for the session's conversation.
 */
used_tokens: bigint,
/**
 * Output tokens reserved for the model's reply (the configured
 * `max_output_tokens`, also the per-request provider hard cap).
 */
output_reserve_tokens: bigint,
/**
 * Safe available input budget = window − reserve − used. `None` when the
 * window is unknown.
 */
safe_input_tokens: bigint | null,
/**
 * Which metadata tier the window came from: `config` (explicit TOML),
 * `provider` (`GET /models` discovery), `community` (models.dev),
 * `registry` (built-in static tables), or `unknown` (no window).
 */
window_source: string,
/**
 * True when the window is not an explicit user configuration (i.e.
 * anything other than `config`); discovered tiers can change as
 * fetches land.
 */
estimated: boolean, };
