// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextBudgetDto } from "./ContextBudgetDto";
import type { TodoTask } from "./TodoTask";
import type { ToolCall } from "./ToolCall";

/**
 * One event payload delivered by the bridge. The `type` field is the
 * discriminator; the owning `session_id` and the process-global `cursor` live
 * on the [`Envelope`] wrapper.
 */
export type Event = { "type": "reasoning_delta", delta: string, } | { "type": "reasoning_completed" } | { "type": "provider_retry", attempt: number, reason: string, delay_ms: bigint, } | { "type": "model_streaming" } | { "type": "web_search_started", query: string, } | { "type": "web_search_result", title: string, url: string, snippet: string, } | { "type": "web_search_completed", count: number, } | { "type": "cancelled", reason: string, } | { "type": "text_delta", delta: string, } | { "type": "tool_call_streaming", name: string | null, received_bytes: bigint, } | { "type": "approval", approval_id: string, call: ToolCall, reason: string, source_session_id: string | null, source_title: string | null, } | { "type": "approval_resolved", approval_id: string, approved: boolean, } | { "type": "tool_started", call: ToolCall, } | { "type": "tool_finished", call: ToolCall, result: string, } | { "type": "usage", input_tokens: bigint, output_tokens: bigint, total_tokens: bigint, } | { "type": "completed" } | { "type": "failed", error: string, } | { "type": "sessions_changed" } | { "type": "child_session_progress", child_session_id: string, status: string, turn: number, max_turns: number, tool: string | null, } | { "type": "local_command_finished", command: string, result: string, } | { "type": "compaction_started" } | { "type": "compaction_completed", hidden: number, } | { "type": "compaction_failed", error: string, } | { "type": "todo_updated", tasks: Array<TodoTask>, } | { "type": "transcript_invalidated" } | { "type": "context_updated", budget: ContextBudgetDto, } | { "type": "resync_required" };
