// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bounded, workspace-scoped long-term memory row. Candidates are never
 * injected into model requests until explicitly confirmed by the user.
 */
export type MemoryDto = { id: bigint, kind: string, title: string, content: string, topic: string | null, status: string, source_session_id: string | null, source_turn_id: string | null, source_message_id: bigint | null, evidence: string | null, created_at: string, updated_at: string, confirmed_at: string | null, recallable: boolean, };
