// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCall } from "./ToolCall";

/**
 * A single message in a session's transcript, in display shape. The `kind`
 * field is the discriminator; provider-private payloads are translated into a
 * display-safe shape and never leaked as raw JSON.
 */
export type MessageDto = { "kind": "user", id: bigint, content: string, created_at: string, } | { "kind": "assistant", id: bigint, content: string, created_at: string, } | { "kind": "system", id: bigint, content: string, created_at: string, } | { "kind": "thinking", id: bigint, content: string, created_at: string, } | { "kind": "context", id: bigint, label: string, content: string, created_at: string, } | { "kind": "compaction_summary", id: bigint, content: string, created_at: string, } | { "kind": "tool", id: bigint, call_id: string, name: string, arguments: any, status: string, result: string | null, created_at: string, } | { "kind": "tool_calls", id: bigint, calls: Array<ToolCall>, created_at: string, } | { "kind": "tool_output", id: bigint, call_id: string, output: string, created_at: string, };
