// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageDto } from "./MessageDto";

/**
 * One page of a session transcript, in display (oldest→newest) order.
 *
 * `next_before` is an opaque cursor for fetching the previous (older) page:
 * echo it back as the `before` query parameter. `has_more` is true when older
 * messages exist.
 */
export type MessagePage = { messages: Array<MessageDto>, next_before: bigint | null, has_more: boolean, };
