// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A persisted incomplete assistant answer, shown as "未完成" and never fed
 * back into the model context or `previous_response_id`.
 */
export type PartialDto = { content: string, created_at: string, };
