// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-secret provider connection profile for settings screens. `id` is the
 * stable provider identity the set-provider endpoint accepts (a built-in preset
 * key such as `"deepseek"`, or a generated `"custom-<uuid>"`); `preset` is the
 * template/family key (`"deepseek"`, `"custom"`, …) and `kind` is the
 * `ProviderKind` wire tag (`"responses"` / `"chat_completions"`). `name` and
 * `enabled_models` are reserved for named custom providers and a future
 * selectable model list. API keys are never part of any DTO.
 */
export type ProviderProfileDto = { id: string, preset: string,
/**
 * Display name for a named provider; empty for built-ins (the UI falls
 * back to the preset label).
 */
name: string, kind: string, model: string, base_url: string,
/**
 * Models the user selected for this provider. Empty means "unrestricted";
 * reserved for a future model-picker and not yet enforced at request time.
 */
enabled_models: Array<string>, };
