// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderProfileDto } from "./ProviderProfileDto";

/**
 * Provider settings for `GET /api/v2/config/provider`: the active profile,
 * the saved per-preset profiles, and which presets currently have a usable
 * API key (cache-only lookup: startup unlock, environment preload, and keys
 * stored during this run). Absence from `connected` means "no key resolved
 * yet", not a definitive "never configured".
 */
export type ProviderSettingsDto = { active: ProviderProfileDto, saved: Array<ProviderProfileDto>, connected: Array<string>, };
