// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-secret provider connection profile for settings screens. `preset` is
 * the `ProviderPreset` key id (`"deepseek"`) - the same identifier the
 * set-provider endpoint accepts - and `kind` is the `ProviderKind` wire tag
 * (`"responses"` / `"chat_completions"`). API keys are never part of any DTO.
 */
export type ProviderProfileDto = { preset: string, kind: string, model: string, base_url: string, };
