// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderModelDto } from "./ProviderModelDto";

/**
 * The provider's model list for settings screens, served from the
 * `model_metadata` cache after an explicit or triggered refresh.
 * `fetched_at` is the Unix seconds of the last successful provider fetch
 * (`None` when only static lists are available).
 */
export type ProviderModelsDto = { models: Array<ProviderModelDto>, fetched_at: bigint | null, };
