// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One model entry of the provider's `GET /models` list. Metadata fields are
 * `null` when the endpoint does not report them (plain OpenAI-compatible
 * servers list ids only; OpenRouter and LM Studio expose window/output
 * limits).
 */
export type ProviderModelDto = { id: string, context_window_tokens: bigint | null, max_output_tokens: number | null, };
