// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serialized form of a session used by [`AppSnapshotV2`].
 */
export type SessionStateDto = { id: string, title: string, parent_id: string | null, busy: boolean, phase: string, status: string, };
