// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoStatus } from "./TodoStatus";

export type TodoTask = { id: string, title: string, status: TodoStatus, created_at: string, updated_at: string, };
