// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolCall = { id: string, name: string, 
/**
 * Arbitrary tool arguments; the frontend treats them as opaque JSON.
 */
arguments: any, };
